-- Run this once in Supabase: SQL Editor > New query > Run.
-- Authentication users are stored securely by Supabase in auth.users.

create table if not exists public.feedback (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  reason text not null default 'feedback',
  message text not null check (char_length(message) between 1 and 2000),
  created_at timestamptz not null default now()
);

alter table public.feedback enable row level security;

create policy "Authenticated users can submit feedback"
on public.feedback
for insert
to authenticated
with check (auth.uid() = user_id);

create policy "Users can read their own feedback"
on public.feedback
for select
to authenticated
using (auth.uid() = user_id);
