-- Run this once in Supabase: SQL Editor > New query > Run.
-- Authentication users are stored securely by Supabase in auth.users.

create table if not exists public.feedback (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  reason text not null default 'feedback',
  message text not null check (char_length(message) between 1 and 2000),
  created_at timestamptz not null default now()
);

alter table public.feedback enable row level security;

drop policy if exists "Authenticated users can submit feedback" on public.feedback;
create policy "Authenticated users can submit feedback"
on public.feedback
for insert
to authenticated
with check (auth.uid() = user_id);

drop policy if exists "Users can read their own feedback" on public.feedback;
create policy "Users can read their own feedback"
on public.feedback
for select
to authenticated
using (auth.uid() = user_id);

-- Admin dashboard setup. Run this full file once in Supabase SQL Editor.
create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  display_name text,
  role text not null default 'user' check (role in ('user', 'admin')),
  created_at timestamptz not null default now()
);

create or replace function public.handle_new_user()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  insert into public.profiles (id, display_name)
  values (new.id, coalesce(new.raw_user_meta_data ->> 'display_name', ''))
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created after insert on auth.users
for each row execute procedure public.handle_new_user();

-- Give already-existing accounts a profile as well.
insert into public.profiles (id, display_name)
select id, coalesce(raw_user_meta_data ->> 'display_name', '') from auth.users
on conflict (id) do nothing;

create or replace function public.is_admin()
returns boolean language sql stable security definer set search_path = public as $$
  select exists (select 1 from public.profiles where id = auth.uid() and role = 'admin');
$$;

alter table public.profiles enable row level security;
drop policy if exists "Users can view their own profile" on public.profiles;
create policy "Users can view their own profile" on public.profiles for select to authenticated using (id = auth.uid());

create table if not exists public.universities (
  id bigint generated by default as identity primary key,
  name text not null unique,
  types text[] not null default '{}',
  regions text[] not null default '{}',
  page_url text, image_url text, description text,
  latitude numeric, longitude numeric,
  created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);

create or replace function public.set_updated_at()
returns trigger language plpgsql as $$ begin new.updated_at = now(); return new; end; $$;
drop trigger if exists universities_updated_at on public.universities;
create trigger universities_updated_at before update on public.universities
for each row execute procedure public.set_updated_at();

alter table public.universities enable row level security;
drop policy if exists "Anyone can read universities" on public.universities;
create policy "Anyone can read universities" on public.universities for select to anon, authenticated using (true);
drop policy if exists "Admins can manage universities" on public.universities;
create policy "Admins can manage universities" on public.universities for all to authenticated
using (public.is_admin()) with check (public.is_admin());
drop policy if exists "Admins can manage feedback" on public.feedback;
create policy "Admins can manage feedback" on public.feedback for all to authenticated
using (public.is_admin()) with check (public.is_admin());

-- After creating your account, promote it with your actual email:
-- update public.profiles set role = 'admin'
-- where id = (select id from auth.users where email = 'your-email@example.com');
